# Generated by Django 4.1.3 on 2022-12-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Название теста')),
                ('title', models.CharField(max_length=100, verbose_name='Тест')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Название темы набора тестов')),
                ('title', models.CharField(max_length=100, verbose_name='Тема')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('nametest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Вопросы', to='tests.nametest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='nametest',
            name='settest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Тест', to='tests.settests', verbose_name='Тема набора тестов'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Правильность')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ответы', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
