# Generated by Django 4.1.3 on 2022-12-21 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='settests',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='nametest',
            name='settest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.settests', verbose_name='Тема набора тестов'),
        ),
        migrations.AlterField(
            model_name='nametest',
            name='slug',
            field=models.SlugField(verbose_name='Ссылка на тест'),
        ),
        migrations.AlterField(
            model_name='question',
            name='nametest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.nametest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='settests',
            name='slug',
            field=models.SlugField(verbose_name='Ссылка на тему'),
        ),
        migrations.CreateModel(
            name='CountAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=255, verbose_name='Результат')),
                ('nametest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.nametest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
